#!/bin/sh

# Prflr monitoring
set -e

# Must be a valid filename
NAME=prflr
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/var/www/prflr/bin/prflr
DAEMON_OPTS="--baz=quux"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
    start-stop-daemon --start -bm --quiet --pidfile $PIDFILE --exec $DAEMON
        echo "."
    ;;
  stop)
        echo -n "Stopping daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        echo "."
    ;;
  restart)
        echo -n "Restarting daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
    start-stop-daemon --start -bm --quiet --pidfile $PIDFILE --exec $DAEMON
    echo "."
    ;;

  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0